import type { QuizUser } from "./types";

export const MOCK_USERS: Array<QuizUser & { password: string }> = [
  {
    id: "u-candidate",
    email: "candidate@test.io",
    password: "candidate123",
    firstName: "Jean",
    lastName: "Dupont",
    phone: "+261 34 12 345 67",
    profile: "Étudiant",
    linkedin: "linkedin.com/in/jean-dupont",
    role: "candidate",
    provider: "email",
    avatarColor: "oklch(0.7 0.15 184)",
    registered: true,
  },
  {
    id: "u-juror",
    email: "jury@test.io",
    password: "jury123",
    firstName: "Sarah",
    lastName: "Rakoto",
    role: "juror",
    provider: "email",
    avatarColor: "oklch(0.65 0.18 268)",
    registered: true,
  },
  {
    id: "u-admin",
    email: "admin@test.io",
    password: "admin123",
    firstName: "Admin",
    lastName: "CIRT",
    role: "admin",
    provider: "email",
    avatarColor: "oklch(0.6 0.2 30)",
    registered: true,
  },
  {
    id: "u-new",
    email: "new@test.io",
    password: "new12345",
    firstName: "Nouveau",
    lastName: "Candidat",
    role: "candidate",
    provider: "email",
    registered: false,
  },
];