/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JuryRouteImport } from './routes/jury'
import { Route as DoneRouteImport } from './routes/done'
import { Route as ConditionsGeneralesUtilisationRouteImport } from './routes/conditions-generales-utilisation'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InformationsSlugRouteImport } from './routes/informations.$slug'
import { Route as DetailIdRouteImport } from './routes/detail.$id'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JuryRoute = JuryRouteImport.update({
  id: '/jury',
  path: '/jury',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsGeneralesUtilisationRoute =
  ConditionsGeneralesUtilisationRouteImport.update({
    id: '/conditions-generales-utilisation',
    path: '/conditions-generales-utilisation',
    getParentRoute: () => rootRouteImport,
  } as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationsSlugRoute = InformationsSlugRouteImport.update({
  id: '/informations/$slug',
  path: '/informations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailIdRoute = DetailIdRouteImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/conditions-generales-utilisation': typeof ConditionsGeneralesUtilisationRoute
  '/done': typeof DoneRoute
  '/jury': typeof JuryRoute
  '/login': typeof LoginRoute
  '/partenaires': typeof PartenairesRoute
  '/quiz': typeof QuizRoute
  '/register': typeof RegisterRoute
  '/superadmin': typeof SuperadminRoute
  '/detail/$id': typeof DetailIdRoute
  '/informations/$slug': typeof InformationsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/conditions-generales-utilisation': typeof ConditionsGeneralesUtilisationRoute
  '/done': typeof DoneRoute
  '/jury': typeof JuryRoute
  '/login': typeof LoginRoute
  '/partenaires': typeof PartenairesRoute
  '/quiz': typeof QuizRoute
  '/register': typeof RegisterRoute
  '/superadmin': typeof SuperadminRoute
  '/detail/$id': typeof DetailIdRoute
  '/informations/$slug': typeof InformationsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/conditions-generales-utilisation': typeof ConditionsGeneralesUtilisationRoute
  '/done': typeof DoneRoute
  '/jury': typeof JuryRoute
  '/login': typeof LoginRoute
  '/partenaires': typeof PartenairesRoute
  '/quiz': typeof QuizRoute
  '/register': typeof RegisterRoute
  '/superadmin': typeof SuperadminRoute
  '/detail/$id': typeof DetailIdRoute
  '/informations/$slug': typeof InformationsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/conditions-generales-utilisation'
    | '/done'
    | '/jury'
    | '/login'
    | '/partenaires'
    | '/quiz'
    | '/register'
    | '/superadmin'
    | '/detail/$id'
    | '/informations/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/conditions-generales-utilisation'
    | '/done'
    | '/jury'
    | '/login'
    | '/partenaires'
    | '/quiz'
    | '/register'
    | '/superadmin'
    | '/detail/$id'
    | '/informations/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/conditions-generales-utilisation'
    | '/done'
    | '/jury'
    | '/login'
    | '/partenaires'
    | '/quiz'
    | '/register'
    | '/superadmin'
    | '/detail/$id'
    | '/informations/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BootstrapRoute: typeof BootstrapRoute
  ConditionsGeneralesUtilisationRoute: typeof ConditionsGeneralesUtilisationRoute
  DoneRoute: typeof DoneRoute
  JuryRoute: typeof JuryRoute
  LoginRoute: typeof LoginRoute
  PartenairesRoute: typeof PartenairesRoute
  QuizRoute: typeof QuizRoute
  RegisterRoute: typeof RegisterRoute
  SuperadminRoute: typeof SuperadminRoute
  DetailIdRoute: typeof DetailIdRoute
  InformationsSlugRoute: typeof InformationsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jury': {
      id: '/jury'
      path: '/jury'
      fullPath: '/jury'
      preLoaderRoute: typeof JuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-generales-utilisation': {
      id: '/conditions-generales-utilisation'
      path: '/conditions-generales-utilisation'
      fullPath: '/conditions-generales-utilisation'
      preLoaderRoute: typeof ConditionsGeneralesUtilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informations/$slug': {
      id: '/informations/$slug'
      path: '/informations/$slug'
      fullPath: '/informations/$slug'
      preLoaderRoute: typeof InformationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail/$id': {
      id: '/detail/$id'
      path: '/detail/$id'
      fullPath: '/detail/$id'
      preLoaderRoute: typeof DetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BootstrapRoute: BootstrapRoute,
  ConditionsGeneralesUtilisationRoute: ConditionsGeneralesUtilisationRoute,
  DoneRoute: DoneRoute,
  JuryRoute: JuryRoute,
  LoginRoute: LoginRoute,
  PartenairesRoute: PartenairesRoute,
  QuizRoute: QuizRoute,
  RegisterRoute: RegisterRoute,
  SuperadminRoute: SuperadminRoute,
  DetailIdRoute: DetailIdRoute,
  InformationsSlugRoute: InformationsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
